# fly.toml app configuration file generated for p-server on 2024-10-31T10:34:25Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'p-server'
primary_region = 'sin'

[build]

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
